// made server with http module
const http=require("http");
const fs=require("fs");

const server=http.createServer((req,res)=>{
    let url=req.url;

    if(url==="/"){
        fs.readFile("index.html",(err,data)=>{
            res.writeHead(200,{"content-type":"text/html"});
            res.write(data);
            res.end();
        });
        
    }
    if(url==="/style.css"){
        fs.readFile("style.css",(err,data)=>{
            res.writeHead(200,{"content-type":"text/css"});
            res.write(data);
            res.end();
        });
    }
     if(url==="/icons/Hamburger_icon.svg"){
        fs.readFile("./icons/Hamburger_icon.svg",(err,data)=>{
            res.writeHead(200,{"content-type":"image/svg+xml"});
            res.write(data);
            res.end();
        });
     }
    if(url==="/icons/discount.png"){
        fs.readFile("./icons/discount.png",(err,data)=>{
            res.writeHead(200,{"content-type":"image/png"});
            res.write(data);
            res.end();
        });
     }
    if(url==="/icons/logo.png"){
        fs.readFile("./icons/logo.png",(err,data)=>{
            res.writeHead(200,{"content-type":"image/png"});
            res.write(data);
            res.end();
        });
     }
    if(url==="/icons/fresh.png"){
        fs.readFile("./icons/fresh.png",(err,data)=>{
            res.writeHead(200,{"content-type":"image/png"});
            res.write(data);
            res.end();
        });
     }
    if(url==="/icons/delivery.png"){
        fs.readFile("./icons/delivery.png",(err,data)=>{
            res.writeHead(200,{"content-type":"image/png"});
            res.write(data);
            res.end();
        });
     }
    if(url==="/images/hero_image.png"){
        fs.readFile("./images/hero_image.png",(err,data)=>{
            res.writeHead(200,{"content-type":"image/png"});
            res.write(data);
            res.end();
        });
     }
    if(url==="/images/grid_image1.png"){
        fs.readFile("./images/grid_image1.png",(err,data)=>{
            res.writeHead(200,{"content-type":"image/png"});
            res.write(data);
            res.end();
        });
     }
    if(url==="/images/grid_image2.png"){
        fs.readFile("./images/grid_image2.png",(err,data)=>{
            res.writeHead(200,{"content-type":"image/png"});
            res.write(data);
            res.end();
        });
     }
    if(url==="/images/grid_image3.png"){
        fs.readFile("./images/grid_image3.png",(err,data)=>{
            res.writeHead(200,{"content-type":"image/png"});
            res.write(data);
            res.end();
        });
     }
    if(url==="/images/grid_image4.png"){
        fs.readFile("./images/grid_image4.png",(err,data)=>{
            res.writeHead(200,{"content-type":"image/png"});
            res.write(data);
            res.end();
        });
     }
    if(url==="/images/grid_image5.png"){
        fs.readFile("./images/grid_image5.png",(err,data)=>{
            res.writeHead(200,{"content-type":"image/png"});
            res.write(data);
            res.end();
        });
     }
    if(url==="/images/grid_image6.png"){
        fs.readFile("./images/grid_image6.png",(err,data)=>{
            res.writeHead(200,{"content-type":"image/png"});
            res.write(data);
            res.end();
        });
     }
    if(url==="/images/grid_image7.png"){
        fs.readFile("./images/grid_image7.png",(err,data)=>{
            res.writeHead(200,{"content-type":"image/png"});
            res.write(data);
            res.end();
        });
     }
});

server.listen(80)

